using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Calculator.Core.Contracts.Services;
using Calculator.Core.Helpers;
using Calculator.Core.Models;
using CommunityToolkit.Mvvm.ComponentModel;

namespace Calculator.Core.Services;
public partial class CalculateService : ObservableObject, ICalculateService
{
    // 一般的，进行 Result Operator Operand 的计算，需求 Operator 和 Operand，并将更改应用到 Result 和 Expression
    // 特别的，对于 Invert XPower2 Sqrt 三个操作符，只更改 Result 和 Expression

    [ObservableProperty]
    private CalculateModel _calculate = new()
    {
        Result = "0",
    };

    //public CalculateModel Calculate => _calculate; which is auto generated by [ObservableProperty]

    public void NumpadPress(string number)
    {
        if (Calculate.Result == "0")
        {
            if (number != "0")
            {
                Calculate.Result = number;
            }
        }
        else
        {
            Calculate.Result += number;
        }
    }

    public void BackspacePress()
    {
        if (Calculate.Result == "0" || string.IsNullOrEmpty(Calculate.Result))
        {
            return;
        }

        Calculate.Result = Calculate.Result.Length > 1
            ? Calculate.Result.Substring(0, Calculate.Result.Length - 1)
            : "0";
    }

    public void DecimalPointPress()
    {
        // if . is in the result, return
        if (Calculate.Result.Contains('.'))
        {
            return;
        }
        Calculate.Result += ".";
    }

    public void Paste(string number)
    {
        Calculate.Result = number;
    }

    public void PerformCalculate(OperatorType operatorType)
    {
        switch (operatorType)
        {
            case OperatorType.Add:
            case OperatorType.Subtract:
            case OperatorType.Multiply:
            case OperatorType.Divide:
                PerformFourOperation(operatorType);
                break;
            case OperatorType.Invert:
                PerformInvert();
                break;
            case OperatorType.XPower2:
                PerformXPower2();
                break;
            case OperatorType.Sqrt:
                PerformSquareRoot();
                break;
            case OperatorType.Percent:
                PerformPercent();
                break;
            case OperatorType.Equal:
                PerformEqual();
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(operatorType), operatorType, null);
        }
    }

    public void PerformFourOperation(OperatorType operatorType)
    {
        /*if (string.IsNullOrEmpty(Calculate.Operator.GetOperatorSymbol()))
        {
            Calculate.Expr.Operator = operatorType.GetOperatorSymbol();
            Calculate.Operator = operatorType;
            Calculate.Expr.Operand1 = Calculate.Result;
        }
        else
        {
            var result = CalculateBetweenString.GetStringResult(Calculate.Operand, Calculate.Result, Calculate.Expr.Operator);
            Calculate.Expr.Operand1 = Calculate.Result = result;
            Calculate.Expr.Operator = operatorType.GetOperatorSymbol();
            Calculate.Operator = operatorType;
        }*/
    }

    public void PerformInvert()
    {
    
    }

    public void PerformXPower2()
    {

    }

    public void PerformSquareRoot()
    {
    
    }

    public void PerformPercent()
    {
    
    }

    public void PerformEqual()
    {
    
    }
}
